version: '3'

networks:
  localnet:
    driver: bridge

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: product_feed
      MYSQL_ROOT_PASSWORD: sadasada
      MYSQL_USER: feeduser
      MYSQL_PASSWORD: sadasada
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - localnet
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
      - localnet
    depends_on:
      - db
volumes:
  db_data: